# Generated by Django 5.0.6 on 2024-06-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_business_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
