# Generated by Django 5.0.6 on 2024-07-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_business_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='barangay',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='municipality',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
