# Generated by Django 5.0.6 on 2024-07-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_barangay_profile_business_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='business_pic',
        ),
    ]
