# Generated by Django 5.0.6 on 2024-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_account',
            field=models.TextField(blank=True),
        ),
    ]
